DROP TABLE "MEMBER_EX_SET";
DROP TABLE "FOOD";
DROP TABLE "MEMBER_WEIGHT";
DROP TABLE "BOARD";
DROP TABLE "FOOD_API";
DROP TABLE "DIET";
DROP TABLE "DAY_DIET";
DROP TABLE "EXERCISE";
DROP TABLE "NOTICE";
DROP TABLE "MEMBER";
DROP TABLE "ADMIN";
DROP TABLE "USERS";
DROP TABLE "CALENDAR";

CREATE TABLE "BOARD" (
	"COMMENT_NUM"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR(20)		NOT NULL,
	"BOARD_TITLE"	VARCHAR(200)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR(1000)		NULL,
	"BOARD_COUNT"	NUMBER		NOT NULL,
	"BOARD_DATE"	DATE		NOT NULL
);

CREATE TABLE "MEMBER" (
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MNAME"	VARCHAR2(20)		NOT NULL,
	"MEMAIL"	VARCHAR2(50)		NOT NULL,
	"MBIRTHDAY"	NUMBER		NULL,
	"GENDER"	CHAR(1)		NOT NULL,
	"ADDRESS"	VARCHAR2(40)		NULL,
	"HEIGHT"	NUMBER		NULL,
	"WEIGHT"	NUMBER		NULL,
	"GOOGLEID"	VARCHAR2(63)		NULL,
	"NAVERID"	VARCHAR2(63)		NULL,
	"KAKAOID"	VARCHAR2(63)		NULL
);

COMMENT ON COLUMN "MEMBER"."MNAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."MBIRTHDAY" IS 'YYYY-MM-DD';

COMMENT ON COLUMN "MEMBER"."GENDER" IS 'MAN, FEMALE';

COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER"."HEIGHT" IS '키';

COMMENT ON COLUMN "MEMBER"."WEIGHT" IS '몸무게';

COMMENT ON COLUMN "MEMBER"."GOOGLEID" IS '구글ID';

COMMENT ON COLUMN "MEMBER"."NAVERID" IS '네이버ID';

COMMENT ON COLUMN "MEMBER"."KAKAOID" IS '카카오ID';

CREATE TABLE "ADMIN" (
	"ADMIN_ID"	VARCHAR(20)		NOT NULL,
	"ADMIN_PWD"	VARCHAR2(20)		NOT NULL,
	"ADMIN_NAME"	VARCHAR(20)		NOT NULL,
	"ADMIN_EMAIL"	VARCHAR(50)		NOT NULL
);

CREATE TABLE "EXERCISE" (
	"ECODE"	VARCHAR(20)		NOT NULL,
	"EX_NAME"	VARCHAR2(20)		NOT NULL,
	"PART"	VARCHAR2(30)		NOT NULL,
	"EPOSE"	VARCHAR2(2000)		NOT NULL,
	"EPOSE_LINK"	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "EXERCISE"."EPOSE_LINK" IS '유튜브 자세화면 보이게함';

CREATE TABLE "FOOD" (
	"FOOD_CD"	VARCHAR(20)		NOT NULL,
	"MEAL_CODE"	VARCHAR(100)		NOT NULL,
	"FOOD_QUALITY"	NUMBER		NOT NULL

);

COMMENT ON COLUMN "FOOD"."MEAL_CODE" IS 'DAY_DIET_KEY+FOOD_TIME';

CREATE TABLE "MEMBER_EX_SET" (
	"DAY_EX_SET"	VARCHAR2(70)		NOT NULL,
	"TODAY"	VARCHAR(255)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"ECODE"	VARCHAR(20)		NOT NULL,
	"EX_NAME"	VARCHAR2(20)		NOT NULL,
	"EXERCISE_SET"	NUMBER		NOT NULL,
	"EXERCIES_NUMBER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER_EX_SET"."DAY_EX_SET" IS '날짜,아이디,운동코드조합';

CREATE TABLE "FOOD_API" (
	"FOOD_CD"	VARCHAR(20)		NOT NULL,
	"FOOD_NAME"	VARCHAR(20)		NOT NULL,
	"CALORIE"	NUMBER		NULL,
	"CRABS"	NUMBER		NULL,
	"PROTEIN"	NUMBER		NULL,
	"FAT"	NUMBER		NULL
);

CREATE TABLE "DAY_DIET" (
	"DAY_DIET_CODE"	VARCHAR(20)		NOT NULL,
	"TODAY"	VARCHAR(255)		NOT NULL,
	"MEMBER_ID"	VARCHAR(20)		NOT NULL,
	"FEEDBACK"	VARCHAR(2000)		NULL
);

COMMENT ON COLUMN "DAY_DIET"."DAY_DIET_CODE" IS 'FOOD_DATE+ID';

CREATE TABLE "NOTICE" (
	"NOTICE_NUMBER"	NUMBER		NOT NULL,
	"ADMIN_ID"	VARCHAR(20)		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(100)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"NOTICE_VIEW"	NUMBER		NOT NULL,
	"NOTICE_DATE"	DATE		NOT NULL
);

CREATE TABLE "USERS" (
	"USER_ID"	VARCHAR(20)		NOT NULL,
	"USER_PWD"	VARCHAR(80)		NOT NULL,
	"USER_ENABLED"	number	DEFAULT 1	NOT NULL,
	"AUTHORITIES"	varchar(20)		NOT NULL
);

COMMENT ON COLUMN "USERS"."USER_ENABLED" IS '기본값: 1, 나머지: 0';

CREATE TABLE "MEMBER_WEIGHT" (
	"USER_ID"	VARCHAR(20)		NOT NULL,
	"DATE"	DATE		NOT NULL,
	"WEIGHT"	NUMBER		NOT NULL,
	"MUSCLE_MASS"	NUMBER		NOT NULL,
	"BODY_FAT_PET"	NUMBER		NOT NULL
);

CREATE TABLE "DIET" (
	"MEAL_CODE"	VARCHAR(20)		NOT NULL,
	"DAY_DIET_CODE"	VARCHAR(20)		NOT NULL,
	"FOOD_TIME"	VARCHAR(20)		NULL
);

COMMENT ON COLUMN "DIET"."MEAL_CODE" IS 'DAY_DIET_KEY+FOOD_TIME';

COMMENT ON COLUMN "DIET"."DAY_DIET_CODE" IS 'FOOD_DATE+ID';

COMMENT ON COLUMN "DIET"."FOOD_TIME" IS '아침이면 A, 점심이면 B, 저녁이면 C, 아점이면 X, 점저면Y, 야식은 Z';

CREATE TABLE "CALENDAR" (
	"TODAY"	VARCHAR(255)		NOT NULL
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"COMMENT_NUM"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ADMIN_ID"
);

ALTER TABLE "EXERCISE" ADD CONSTRAINT "PK_EXERCISE" PRIMARY KEY (
	"ECODE",
	"EX_NAME"
);

ALTER TABLE "FOOD" ADD CONSTRAINT "PK_FOOD" PRIMARY KEY (
	"FOOD_CD"
);

ALTER TABLE "MEMBER_EX_SET" ADD CONSTRAINT "PK_MEMBER_EX_SET" PRIMARY KEY (
	"DAY_EX_SET"
);

ALTER TABLE "FOOD_API" ADD CONSTRAINT "PK_FOOD_API" PRIMARY KEY (
	"FOOD_CD"
);

ALTER TABLE "DAY_DIET" ADD CONSTRAINT "PK_DAY_DIET" PRIMARY KEY (
	"DAY_DIET_CODE"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NUMBER",
	"ADMIN_ID"
);

ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "MEMBER_WEIGHT" ADD CONSTRAINT "PK_MEMBER_WEIGHT" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "DIET" ADD CONSTRAINT "PK_DIET" PRIMARY KEY (
	"MEAL_CODE"
);

ALTER TABLE "CALENDAR" ADD CONSTRAINT "PK_CALENDAR" PRIMARY KEY (
	"TODAY"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_USERS_TO_MEMBER_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "USERS" (
	"USER_ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_USERS_TO_ADMIN_1" FOREIGN KEY (
	"ADMIN_ID"
)
REFERENCES "USERS" (
	"USER_ID"
);

ALTER TABLE "FOOD" ADD CONSTRAINT "FK_FOOD_API_TO_FOOD_1" FOREIGN KEY (
	"FOOD_CD"
)
REFERENCES "FOOD_API" (
	"FOOD_CD"
);

ALTER TABLE "FOOD" ADD CONSTRAINT "FK_DIET_TO_FOOD_1" FOREIGN KEY (
	"MEAL_CODE"
)
REFERENCES "DIET" (
	"MEAL_CODE"
);

ALTER TABLE "MEMBER_EX_SET" ADD CONSTRAINT "FK_CALENDAR_TO_MEMBER_EX_SET_1" FOREIGN KEY (
	"TODAY"
)
REFERENCES "CALENDAR" (
	"TODAY"
);

ALTER TABLE "MEMBER_EX_SET" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_EX_SET_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "MEMBER_EX_SET" ADD CONSTRAINT "FK_EXERCISE_TO_MEMBER_EX_SET_1" FOREIGN KEY (
	"ECODE",
	"EX_NAME"
)
REFERENCES "EXERCISE" (
	"ECODE",
	"EX_NAME"
);


ALTER TABLE "DAY_DIET" ADD CONSTRAINT "FK_CALENDAR_TO_DAY_DIET_1" FOREIGN KEY (
	"TODAY"
)
REFERENCES "CALENDAR" (
	"TODAY"
);

ALTER TABLE "DAY_DIET" ADD CONSTRAINT "FK_MEMBER_TO_DAY_DIET_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_ADMIN_TO_NOTICE_1" FOREIGN KEY (
	"ADMIN_ID"
)
REFERENCES "ADMIN" (
	"ADMIN_ID"
);

ALTER TABLE "MEMBER_WEIGHT" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_WEIGHT_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "DIET" ADD CONSTRAINT "FK_DAY_DIET_TO_DIET_1" FOREIGN KEY (
	"DAY_DIET_CODE"
)
REFERENCES "DAY_DIET" (
	"DAY_DIET_CODE"
);


--users
INSERT into users  VALUES ('test1', 'test1', 0, 'member');
INSERT into users  VALUES ('admin1', 'admin1', 1, 'admin');
--member
insert into member values ('test1','테스트', 'test1@gmail.com', '950718', 'M', '강남구 강남역', 180, 77, 'test1@gmail.com','test1@naver.com','test1@nate.com');
--CALENDAR
INSERT INTO CALENDAR VALUES ('230904');
--exercise
insert into exercise (ecode, ex_name,part, epose, epose_link) values(10001,'덤벨 리스트 컬','팔','1.팔뚝을 벤치에 기대고 손바닥이 위쪽을 향하도록 덤벨을 잡습니다.2.손목을 반원 모양으로 천천히 위쪽으로 구부립니다.3.시작 위치로 돌아가서 반복하세요.' ,'<iframe width="853" height="480" src="https://www.youtube.com/embed/S-ynXc4M-mY" title="Simplified: Wrist Curl Quick #Howto" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>');
--member_ex_set
insert into member_ex_set values ('230904test110001','230904','test1', 10001, '덤벨 리스트 컬', 5, 10);
--member_weight
insert into member_weight values ('test1', '230904', 77, 36, 25);
--board
insert into BOARD values (1,'test1', '게시글 테스트 제목', '게시글 테스트 내용', 1, '230904');
--day_diet
insert into day_diet values ('230904test1','230904', 'test1','저녁에 단백질이 부족함');
--diet
insert into diet values ('230904test1A', '230904test1', 'A');
--food_api
insert into food_api values ('D00007','닭갈비',595.61,44.9,45.9,25.8);
--FOOD
insert into food values ('D00007','230904test1A',1);
--admin
insert into admin values ('admin1', 'admin1','관리자1','admin1@gmail.com');
--notice
insert into notice values (1,'admin1','공지사항 제목', '공지사항 내용', 1, '230904');