DROP TABLE "SALES_INFO";
DROP TABLE "CUSTOMER_INFO";

CREATE TABLE "CUSTOMER_INFO" (
	"CUSTNO"	NUMBER(6)		NOT NULL,
	"CUSTNAME"	VARCHAR2(20)		NULL,
	"PHONE"	VARCHAR2(13)		NULL,
	"ADDRESS"	VARCHAR2(60)		NULL,
	"JOINDATE"	DATE		NULL,
	"GRADE"	CHAR(1)		NULL,
	"CITY"	CHAR(2)		NULL
);

COMMENT ON COLUMN "CUSTOMER_INFO"."CUSTNO" IS '회원번호';

COMMENT ON COLUMN "CUSTOMER_INFO"."CUSTNAME" IS '회원성명';

COMMENT ON COLUMN "CUSTOMER_INFO"."PHONE" IS '연락처';

COMMENT ON COLUMN "CUSTOMER_INFO"."ADDRESS" IS '주소';

COMMENT ON COLUMN "CUSTOMER_INFO"."JOINDATE" IS '가입일자';

COMMENT ON COLUMN "CUSTOMER_INFO"."GRADE" IS '고객코드';

COMMENT ON COLUMN "CUSTOMER_INFO"."CITY" IS '도시코드';


CREATE TABLE "SALES_INFO" (
	"SALENOL"	NUMBER(8)		NOT NULL,
	"CUSTNO"	NUMBER(6)		NOT NULL,
	"PCOST"	NUMBER(8)		NULL,
	"AMOUNT"	NUMBER(4)		NULL,
	"PRICE"	NUMBER(8)		NULL,
	"PCODE"	VARCHAR2(4)		NULL,
	"SDATE"	DATE		NULL
);

COMMENT ON COLUMN "SALES_INFO"."SALENOL" IS '판매번호';

COMMENT ON COLUMN "SALES_INFO"."CUSTNO" IS '회원번호';

COMMENT ON COLUMN "SALES_INFO"."PCOST" IS '단가';

COMMENT ON COLUMN "SALES_INFO"."AMOUNT" IS '수량';

COMMENT ON COLUMN "SALES_INFO"."PRICE" IS '가격';

COMMENT ON COLUMN "SALES_INFO"."PCODE" IS '상품코드';

COMMENT ON COLUMN "SALES_INFO"."SDATE" IS '판매일자';

ALTER TABLE "CUSTOMER_INFO" ADD CONSTRAINT "PK_CUSTOMER_INFO" PRIMARY KEY (
	"CUSTNO"
);

ALTER TABLE "SALES_INFO" ADD CONSTRAINT "FK_CUSTOMER_INFO_TO_SALES_INFO_1" FOREIGN KEY (
	"CUSTNO"
)
REFERENCES "CUSTOMER_INFO" (
	"CUSTNO"
);

ALTER TABLE "SALES_INFO" ADD CONSTRAINT "PK_SALES_INFO" PRIMARY KEY (
	"SALENOL",
	"CUSTNO"
);

CREATE TABLE "SALES" (
"CUSTNO"	NUMBER(6) NOT NULL,
"CUSTNAME"	VARCHAR2(20) NULL,
"GRADE"	CHAR(5)		NULL,
"SALES" NUMBER(8) NULL

);

COMMENT ON COLUMN "SALES"."CUSTNO" IS '회원번호';

COMMENT ON COLUMN "SALES"."CUSTNAME" IS '회원이름';

COMMENT ON COLUMN "SALES"."GRADE" IS '등급';

COMMENT ON COLUMN "SALES"."SALES" IS '수량';


INSERT INTO CUSTOMER_INFO ( CUSTNO, CUSTNAME, PHONE, ADDRESS, JOINDATE, GRADE, CITY) VALUES('100001', '김행복', '010-1111-2222', '서울 동대문구 휘경1동', '20151202', 'A', '01');
INSERT INTO CUSTOMER_INFO ( CUSTNO, CUSTNAME, PHONE, ADDRESS, JOINDATE, GRADE, CITY) VALUES('100002', '이춘복', '010-1111-3333', '서울 동대문구 휘경2동', '20151206', 'B', '01');
INSERT INTO CUSTOMER_INFO ( CUSTNO, CUSTNAME, PHONE, ADDRESS, JOINDATE, GRADE, CITY) VALUES('100003', '장믿음', '010-1111-4444', '울릉군 울릉읍 독도1리', '20151001', 'B', '30');
INSERT INTO CUSTOMER_INFO ( CUSTNO, CUSTNAME, PHONE, ADDRESS, JOINDATE, GRADE, CITY) VALUES('100004', '최사랑', '010-1111-5555', '울릉군 울릉읍 독도2리', '20151113', 'A', '30');
INSERT INTO CUSTOMER_INFO ( CUSTNO, CUSTNAME, PHONE, ADDRESS, JOINDATE, GRADE, CITY) VALUES('100005', '진평화', '010-1111-6666', '제주도 제주시 외나무골', '20151225', 'B', '60');
INSERT INTO CUSTOMER_INFO ( CUSTNO, CUSTNAME, PHONE, ADDRESS, JOINDATE, GRADE, CITY) VALUES('100006', '차공단', '010-1111-7777', '제주도 제주시 감나무골', '20151211', 'C', '60');
SELECT * FROM CUSTOMER_INFO;



INSERT INTO SALES (CUSTNO, CUSTNAME, GRADE, SALES ) VALUES('100001','김행복','A','8000');
INSERT INTO SALES (CUSTNO, CUSTNAME, GRADE, SALES ) VALUES('100004','최사랑','A','4900');
INSERT INTO SALES (CUSTNO, CUSTNAME, GRADE, SALES ) VALUES('100003','장믿음','B','3000');
INSERT INTO SALES (CUSTNO, CUSTNAME, GRADE, SALES ) VALUES('100002','이춘복','B','2500');

SELECT * FROM SALES;

desc CUSTOMER_INFO;

commit;